-- Add new RequestStatus enum values for the 12-step request flow
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PILOT_ACCEPTED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'DRONE_ALLOCATED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'OPERATION_COMPLETED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'REPORT_SUBMITTED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'INVOICE_GENERATED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'INVOICE_REVIEWED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'INVOICE_SENT';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'CLOSED';

-- Add lifecycle timestamp and data fields to ServiceRequest
ALTER TABLE "ServiceRequest"
  ADD COLUMN IF NOT EXISTS "pilotAcceptedAt"      TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "droneAllocatedAt"     TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "operationStartedAt"   TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "operationCompletedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "reportNotes"          TEXT,
  ADD COLUMN IF NOT EXISTS "reportSubmittedAt"    TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "invoiceGeneratedAt"   TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "invoiceReviewedAt"    TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "invoiceSentAt"        TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "paymentReceivedAt"    TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "closedAt"             TIMESTAMP(3);
